version: '3.8'

services:
  frontend:
    build: ./code-invaders-front
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./back/back
    ports:
      - "5085:5085"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5085
    volumes:
      - /back/back/Application/radioHack.db:/back/back/Application/radioHack.db
    restart: unless-stopped

#volumes:
#  database_volume: